### ISSUE TITLE
The last block of the workflow has bug in my environment.

### ISSUE THREAD

**Issue by developer-mayuan** [CarlosEvo/alfred_open_iina#1] opened 2017-05-13 19:27 UTC
I can not successfully run your workflow in my environment. I debugged your code and I found the issue exists in the last block. The string output of ruby block contains the character `\n` which should not be contained when feeding to the shell command (I use ZSH instead of BASH, but I think it doesn't matter). I modified it, which is shown in the figure below and it works for me finally. Thanks.

```bash
cd /Applications

open "iina://weblink?url=${1[1,-2]}"
```

<img width="2672" alt="screen shot 2017-05-13 at 3 26 28 pm" src="https://cloud.githubusercontent.com/assets/13360081/26028545/dd2b009a-37f0-11e7-8116-8602c46a7633.png">

**Comment by zoenglinghou** [comment] 2017-05-14 06:28
You are right indeed. Thank you!

The Issue is fixed in the latest commit.

**Closed as completed** 2017-05-14 06:29 UTC
